let bacnet = require('node-bacnet');

const pi = bacnet.enum.PropertyIdentifier;

const ObjectPropertiesArr = [
    pi.OBJECT_IDENTIFIER,
    pi.OBJECT_NAME,
    pi.OBJECT_TYPE,
    pi.PRESENT_VALUE,
    pi.DESCRIPTION,
    pi.STATUS_FLAGS,
    pi.RELIABILITY,
    pi.OUT_OF_SERVICE,
    pi.NETWORK_TYPE,
    pi.PROTOCOL_LEVEL,
    pi.REFERENCE_PORT,
    pi.NETWORK_NUMBER,
    pi.NETWORK_NUMBER_QUALITY,
    pi.CHANGES_PENDING,
    pi.APDU_LENGTH,
    pi.LINK_SPEED,
    pi.BACNET_IP_MODE,
    pi.IP_ADDRESS,
    pi.BACNET_IP_UDP_PORT,
    pi.IP_SUBNET_MASK,
    pi.IP_DEFAULT_GATEWAY,
    pi.BACNET_IP_MULTICAST_ADDRESS,
    pi.IP_DNS_SERVER,
    pi.IP_DHCP_ENABLE,
    pi.BBMD_BROADCAST_DISTRIBUTION_TABLE,
    pi.BBMD_FOREIGN_DEVICE_TABLE,
    pi.BBMD_ACCEPT_FD_REGISTRATIONS,
    pi.FILE_TYPE,
    pi.FILE_SIZE,
    pi.FILE_ACCESS_METHOD,
    pi.RECORD_COUNT,
    pi.NODE_TYPE
];
const ObjectProperties = [
    { id: pi.OBJECT_IDENTIFIER },
    { id: pi.OBJECT_NAME },
    { id: pi.OBJECT_TYPE },
    { id: pi.PRESENT_VALUE },
    // { id: pi.DESCRIPTION },
    // { id: pi.STATUS_FLAGS },
    // { id: pi.RELIABILITY },
    // { id: pi.OUT_OF_SERVICE },
    // { id: pi.NETWORK_TYPE },
    // { id: pi.PROTOCOL_LEVEL },
    // { id: pi.REFERENCE_PORT },
    // { id: pi.NETWORK_NUMBER },
    // { id: pi.NETWORK_NUMBER_QUALITY },
    // { id: pi.CHANGES_PENDING },
    // { id: pi.APDU_LENGTH },
    // { id: pi.LINK_SPEED },
    // { id: pi.BACNET_IP_MODE },
    // { id: pi.IP_ADDRESS },
    // { id: pi.BACNET_IP_UDP_PORT },
    // { id: pi.IP_SUBNET_MASK },
    // { id: pi.IP_DEFAULT_GATEWAY },
    // { id: pi.BACNET_IP_MULTICAST_ADDRESS },
    // { id: pi.IP_DNS_SERVER },
    // { id: pi.IP_DHCP_ENABLE },
    // { id: pi.BBMD_BROADCAST_DISTRIBUTION_TABLE },
    // { id: pi.BBMD_FOREIGN_DEVICE_TABLE },
    // { id: pi.BBMD_ACCEPT_FD_REGISTRATIONS },
    // { id: pi.FILE_TYPE },
    // { id: pi.FILE_SIZE },
    // { id: pi.FILE_ACCESS_METHOD },
    // { id: pi.RECORD_COUNT },
    // { id: pi.NODE_TYPE },
];

module.exports.objs = ObjectProperties;
module.exports.array = ObjectPropertiesArr;